# This is a TOML document.
# Configuration for the application.

# The SQL settings.
[postgresql]
host = "host"
username = "username"
password = "password"
database = "database"
port = 5432
enabled = "true"